# Generated by Django 3.0.5 on 2020-11-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=350)),
                ('response', models.CharField(default='', max_length=350)),
                ('subcat_name', models.CharField(default='', max_length=350)),
                ('page_name', models.CharField(default='', max_length=350)),
                ('article_writer', models.CharField(default='', max_length=350)),
                ('article_time', models.CharField(default='', max_length=350)),
                ('article_title', models.CharField(default='', max_length=1350)),
                ('article_caption', models.CharField(default='', max_length=1350)),
                ('article_txt', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
